/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taller;

import java.util.Date;
import javax.swing.JOptionPane;

import taller.Administrador.ENoExiste;
import taller.Administrador.EYaExiste;

import java.util.*;
import java.awt.HeadlessException;
import java.io.*;

/**
 *
 * @author Simon
 */
public class AgregarVehiculo extends javax.swing.JFrame {

    Mecanico[] mecanicos;
    Cliente[] clientes;

    /**
     * Creates new form AgregarVehiculo
     */
    public AgregarVehiculo() {
        initComponents();

        clientes = new Cliente[0];
        mecanicos = new Mecanico[0];

        cargarFicheros();
    }

    public void cargarFicheros() {
        try {
            FileInputStream fis = new FileInputStream("Clientes.dat");
            ObjectInputStream ois = new ObjectInputStream(fis);
            clientes = (Cliente[]) ois.readObject();
            ois.close();
            fis.close();
        } catch (IOException | ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }

        try {
            FileInputStream fis = new FileInputStream("Mecanicos.dat");
            ObjectInputStream ois = new ObjectInputStream(fis);
            mecanicos = (Mecanico[]) ois.readObject();
            ois.close();
            fis.close();
        } catch (IOException | ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }
    }

    public void guardarFicheros() {
        try {
            FileOutputStream fos = new FileOutputStream("Clientes.dat");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(clientes);
            oos.close();
            fos.close();
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }

        try {
            FileOutputStream fos = new FileOutputStream("Mecanicos.dat");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(mecanicos);
            oos.close();
            fos.close();
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clienteCedula = new javax.swing.JTextField();
        checkMoto = new javax.swing.JCheckBox();
        checkCarro = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        motoPlaca = new javax.swing.JTextField();
        motoColor = new javax.swing.JTextField();
        motoKilometraje = new javax.swing.JTextField();
        motoTiempos = new javax.swing.JTextField();
        carroPlaca = new javax.swing.JTextField();
        carroColor = new javax.swing.JTextField();
        carroKilometraje = new javax.swing.JTextField();
        carroNumeroPuertas = new javax.swing.JTextField();
        botonGuardarMoto = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        carroTraccion = new javax.swing.JTextField();
        carroCheckLlantas = new javax.swing.JCheckBox();
        motoCheckLlantas = new javax.swing.JCheckBox();
        botonGuardarCarro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("AGREGAR VEHÃ�CULO");

        jLabel2.setText("NÃºmero de CÃ©dula:");

        clienteCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteCedulaActionPerformed(evt);
            }
        });

        checkMoto.setText("Moto");
        checkMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMotoActionPerformed(evt);
            }
        });

        checkCarro.setText("Carro");
        checkCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCarroActionPerformed(evt);
            }
        });

        jLabel9.setText("Placa:");

        jLabel10.setText("Color:");

        jLabel11.setText("Kilometraje:");

        jLabel12.setText("Tiempos:");

        jLabel13.setText("Placa:");

        jLabel14.setText("Color:");

        jLabel15.setText("Kilometraje:");

        jLabel16.setText("NÃºmero de Puertas:");

        botonGuardarMoto.setText("Guardar");
        botonGuardarMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					botonGuardarMotoActionPerformed(evt);
				} catch (NumberFormatException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ENoExiste e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (EYaExiste e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jLabel17.setText("TracciÃ³n:");

        carroCheckLlantas.setText("Â¿Llantas Ã³ptimas?");
        carroCheckLlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carroCheckLlantasActionPerformed(evt);
            }
        });

        motoCheckLlantas.setText("Â¿Llantas Ã“ptimas?");

        botonGuardarCarro.setText("Guardar");
        botonGuardarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					botonGuardarCarroActionPerformed(evt);
				} catch (NumberFormatException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (HeadlessException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (EYaExiste e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (ENoExiste e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(254, 254, 254))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(clienteCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(motoCheckLlantas)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkMoto)
                                    .addComponent(motoPlaca)
                                    .addComponent(motoColor)
                                    .addComponent(motoKilometraje)
                                    .addComponent(motoTiempos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(carroColor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(checkCarro)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(carroPlaca)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(carroCheckLlantas)
                                    .addComponent(carroTraccion)
                                    .addComponent(carroNumeroPuertas)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(carroKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(botonGuardarMoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGuardarCarro)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clienteCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkMoto)
                    .addComponent(checkCarro))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(motoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carroPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(motoColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carroColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(motoKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carroKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(motoTiempos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carroNumeroPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(carroTraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motoCheckLlantas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(carroCheckLlantas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardarMoto)
                    .addComponent(botonGuardarCarro))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteCedulaActionPerformed

    private void checkMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMotoActionPerformed
        // TODO add your handling code here:
        if (checkCarro.isSelected()) {
            checkCarro.setSelected(false);
            checkMoto.setSelected(true);
        }

    }//GEN-LAST:event_checkMotoActionPerformed

    private void checkCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCarroActionPerformed
        // TODO add your handling code here:
        if (checkMoto.isSelected()) {
            checkMoto.setSelected(false);
            checkCarro.setSelected(true);
        }
    }//GEN-LAST:event_checkCarroActionPerformed

    private void botonGuardarMotoActionPerformed(java.awt.event.ActionEvent evt) throws NumberFormatException, ENoExiste, EYaExiste {//GEN-FIRST:event_botonGuardarMotoActionPerformed
        // TODO add your handling code here:
        if (clienteCedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos");
        } else {
            String cedula = clienteCedula.getText().trim();

            String mtPlaca = motoPlaca.getText().trim();
            String mtColor = motoColor.getText().trim();
            String mtKilometraje = motoKilometraje.getText().trim();
            String mtTiempos = motoTiempos.getText().trim();
            boolean mtLlantas = motoCheckLlantas.isSelected();
            mtPlaca = mtPlaca.toUpperCase();

            if (checkMoto.isSelected()) {
                if (motoPlaca.getText().isEmpty() || motoColor.getText().isEmpty() || motoKilometraje.getText().isEmpty() || motoTiempos.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Por favor complete todos los campos (MOTO)");
                } else {
                    Administrador a = new Administrador();
                    if (a.existeCedula(cedula)) {
                        if (!a.existeVehiculo(mtPlaca)) {
                            a.addVehiculo(cedula, mtPlaca, mtColor, true, Integer.parseInt(mtKilometraje), mtLlantas, Integer.parseInt(mtTiempos));

                            JOptionPane.showMessageDialog(null, "Guardado Exitoso");
                            //this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Ya existe un vehÃ­culo con placa: " + mtPlaca);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Cliente no encontrado: CC" + cedula);
                    }
                }

            }
        }
    }//GEN-LAST:event_botonGuardarMotoActionPerformed

    private void carroCheckLlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carroCheckLlantasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carroCheckLlantasActionPerformed

    private void botonGuardarCarroActionPerformed(java.awt.event.ActionEvent evt) throws NumberFormatException, HeadlessException, EYaExiste, ENoExiste {//GEN-FIRST:event_botonGuardarCarroActionPerformed
        // TODO add your handling code here:
        if (clienteCedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos");
        } else {
            String cedula = clienteCedula.getText().trim();
            String crPlaca = carroPlaca.getText().trim();
            String crColor = carroColor.getText().trim();
            String crKilometraje = carroKilometraje.getText().trim();
            String crNumPuertas = carroNumeroPuertas.getText().trim();
            String crTraccion = carroTraccion.getText().trim();
            boolean crLlantas = carroCheckLlantas.isSelected();
            crPlaca = crPlaca.toUpperCase();

            if (checkCarro.isSelected()) {
                if (carroPlaca.getText().isEmpty() || carroColor.getText().isEmpty() || carroKilometraje.getText().isEmpty() || carroNumeroPuertas.getText().isEmpty() || carroTraccion.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Por favor complete todos los campos (CARRO)");
                } else {
                    Administrador a = new Administrador();
                    if (a.existeCedula(cedula)) {
                        if (!a.existeVehiculo(crPlaca)) {
                            a.addVehiculo(cedula, crPlaca, crColor, true, Integer.parseInt(crKilometraje), crLlantas, Integer.parseInt(crNumPuertas), crTraccion);

                            JOptionPane.showMessageDialog(null, "Guardado Exitoso");
                            //this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Ya existe un vehÃ­culo con placa: " + crPlaca);
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Cliente no encontrado: CC" + cedula);
                    }

                }
            }
        }
    }//GEN-LAST:event_botonGuardarCarroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarCarro;
    private javax.swing.JButton botonGuardarMoto;
    private javax.swing.JCheckBox carroCheckLlantas;
    private javax.swing.JTextField carroColor;
    private javax.swing.JTextField carroKilometraje;
    private javax.swing.JTextField carroNumeroPuertas;
    private javax.swing.JTextField carroPlaca;
    private javax.swing.JTextField carroTraccion;
    private javax.swing.JCheckBox checkCarro;
    private javax.swing.JCheckBox checkMoto;
    private javax.swing.JTextField clienteCedula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox motoCheckLlantas;
    private javax.swing.JTextField motoColor;
    private javax.swing.JTextField motoKilometraje;
    private javax.swing.JTextField motoPlaca;
    private javax.swing.JTextField motoTiempos;
    // End of variables declaration//GEN-END:variables
}
