/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taller;

import java.util.Date;
import javax.swing.JOptionPane;
import java.util.*;
import java.awt.JobAttributes;
import java.io.*;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Simon
 */
public class AgregarCliente extends javax.swing.JFrame {

    Mecanico[] mecanicos;
    Cliente[] clientes;

    /**
     * Creates new form AgregarCliente
     */
    public AgregarCliente() {
        initComponents();

        clientes = new Cliente[0];
        mecanicos = new Mecanico[0];

        cargarFicheros();
        setResizable(false);
    }

    public void cargarFicheros() {
        try {
            FileInputStream fis = new FileInputStream("Clientes.dat");
            ObjectInputStream ois = new ObjectInputStream(fis);
            clientes = (Cliente[]) ois.readObject();
            ois.close();
            fis.close();
        } catch (IOException | ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }

        try {
            FileInputStream fis = new FileInputStream("Mecanicos.dat");
            ObjectInputStream ois = new ObjectInputStream(fis);
            mecanicos = (Mecanico[]) ois.readObject();
            ois.close();
            fis.close();
        } catch (IOException | ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }
    }

    public void guardarFicheros() {
        try {
            FileOutputStream fos = new FileOutputStream("Clientes.dat");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(clientes);
            oos.close();
            fos.close();
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }

        try {
            FileOutputStream fos = new FileOutputStream("Mecanicos.dat");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(mecanicos);
            oos.close();
            fos.close();
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        clienteNombre = new javax.swing.JTextField();
        clienteCedula = new javax.swing.JTextField();
        clienteFNDia = new javax.swing.JTextField();
        clienteDireccion = new javax.swing.JTextField();
        clienteTelefono = new javax.swing.JTextField();
        clienteCorreo = new javax.swing.JTextField();
        clienteFNMes = new javax.swing.JTextField();
        clienteFNAno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        checkMoto = new javax.swing.JCheckBox();
        checkCarro = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        motoPlaca = new javax.swing.JTextField();
        motoColor = new javax.swing.JTextField();
        motoKilometraje = new javax.swing.JTextField();
        motoTiempos = new javax.swing.JTextField();
        carroPlaca = new javax.swing.JTextField();
        carroColor = new javax.swing.JTextField();
        carroKilometraje = new javax.swing.JTextField();
        carroNumeroPuertas = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        carroTraccion = new javax.swing.JTextField();
        carroCheckLlantas = new javax.swing.JCheckBox();
        motoCheckLlantas = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("AGREGAR CLIENTE");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Número de Documento:");

        jLabel4.setText("Fecha de Nacimiento:");

        jLabel5.setText("Dirección:");

        jLabel6.setText("Número de Teléfono:");

        jLabel7.setText("Correo Electrónico:");

        jLabel8.setText("D/M/AAAA");

        checkMoto.setText("Moto");
        checkMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMotoActionPerformed(evt);
            }
        });

        checkCarro.setText("Carro");
        checkCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCarroActionPerformed(evt);
            }
        });

        jLabel9.setText("Placa:");

        jLabel10.setText("Color:");

        jLabel11.setText("Kilometraje:");

        jLabel12.setText("Tiempos:");

        jLabel13.setText("Placa:");

        jLabel14.setText("Color:");

        jLabel15.setText("Kilometraje:");

        jLabel16.setText("Número de Puertas:");

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        jLabel17.setText("Tracción:");

        carroCheckLlantas.setText("¿Llantas óptimas?");
        carroCheckLlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carroCheckLlantasActionPerformed(evt);
            }
        });

        motoCheckLlantas.setText("¿Llantas óptimas?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(282, 282, 282))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(motoCheckLlantas)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkMoto)
                                    .addComponent(motoPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(motoColor)
                                    .addComponent(motoKilometraje)
                                    .addComponent(motoTiempos))))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(carroColor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(checkCarro)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(carroPlaca)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clienteFNDia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clienteFNMes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clienteFNAno, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(carroCheckLlantas)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(carroTraccion)
                                    .addComponent(carroNumeroPuertas)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(carroKilometraje))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(259, 259, 259)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonGuardar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(clienteTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addComponent(clienteDireccion)
                                .addComponent(clienteCedula)
                                .addComponent(clienteNombre)
                                .addComponent(clienteCorreo)))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(clienteCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(clienteFNDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteFNMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteFNAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(clienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(clienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(clienteCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkMoto)
                    .addComponent(checkCarro))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(motoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carroPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(motoColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carroColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(motoKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carroKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(motoTiempos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carroNumeroPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(carroTraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motoCheckLlantas))
                .addGap(18, 18, 18)
                .addComponent(carroCheckLlantas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(botonGuardar)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMotoActionPerformed
        // TODO add your handling code here:
        if (checkCarro.isSelected()) {
            checkCarro.setSelected(false);
            checkMoto.setSelected(true);
        }


    }//GEN-LAST:event_checkMotoActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
        if (clienteNombre.getText().isEmpty() || clienteCedula.getText().isEmpty()
                || clienteDireccion.getText().isEmpty() || clienteTelefono.getText().isEmpty()
                || clienteCorreo.getText().isEmpty() || clienteFNDia.getText().isEmpty()
                || clienteFNMes.getText().isEmpty() || clienteFNAno.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos");
        } else {
        	if (Integer.parseInt(clienteFNDia.getText().trim()) > 0 && Integer.parseInt(clienteFNMes.getText().trim()) > 0 && Integer.parseInt(clienteFNAno.getText().trim()) > 1900) {
        		 String nombre = clienteNombre.getText().trim();
                 String cedula = clienteCedula.getText().trim();
                 String direccion = clienteDireccion.getText().trim();
                 String telefono = clienteTelefono.getText().trim();
                 String correo = clienteCorreo.getText().trim();

                 int FNDia = Integer.parseInt(clienteFNDia.getText().trim());
                 int FNMes = Integer.parseInt(clienteFNMes.getText().trim());
                 int FNAno = Integer.parseInt(clienteFNAno.getText().trim());
                 LocalDate FN1 = LocalDate.of(FNAno, FNMes, FNDia);
                 ZoneId dziD = ZoneId.systemDefault();
                 Date FN = Date.from(FN1.atStartOfDay(dziD).toInstant());

                 String mtPlaca = motoPlaca.getText().trim();
                 String mtColor = motoColor.getText().trim();
                 String mtKilometraje = motoKilometraje.getText().trim();
                 String mtTiempos = motoTiempos.getText().trim();
                 boolean mtLlantas = motoCheckLlantas.isSelected();

                 String crPlaca = carroPlaca.getText().trim();
                 String crColor = carroColor.getText().trim();
                 String crKilometraje = carroKilometraje.getText().trim();
                 String crNumPuertas = carroNumeroPuertas.getText().trim();
                 String crTraccion = carroTraccion.getText().trim();
                 boolean crLlantas = carroCheckLlantas.isSelected();
                 mtPlaca = mtPlaca.toUpperCase();
                 crPlaca = crPlaca.toUpperCase();

                 if (checkMoto.isSelected()) {
                     if (motoPlaca.getText().isEmpty() || motoColor.getText().isEmpty() || motoKilometraje.getText().isEmpty() || motoTiempos.getText().isEmpty()) {
                         JOptionPane.showMessageDialog(null, "Por favor complete todos los campos (MOTO)");
                     } else {
                         Administrador a = new Administrador();
                         try {
                             if (!a.existeCedula(cedula)) {
                                 if (!a.existeVehiculo(mtPlaca)) {
                                     Date hoy = Calendar.getInstance().getTime();
                                     try {
                                         a.addCliente(nombre, cedula, FN, direccion, telefono, correo, hoy, mtPlaca, mtColor, true, Integer.parseInt(mtKilometraje), mtLlantas, Integer.parseInt(mtTiempos));
                                     } catch (Administrador.ENoExiste ex) {
                                         JOptionPane.showMessageDialog(null, ex.getMessage());
                                     } catch (Administrador.EVectorNulo ex) {
                                         JOptionPane.showMessageDialog(null, ex.getMessage());
                                     }
                                     
                                     JOptionPane.showMessageDialog(null, "Guardado Exitoso");
                                     this.dispose();
                                 } else {
                                     JOptionPane.showMessageDialog(null, "Ya existe un vehículo con placa: " + mtPlaca);
                                 }
                             } else {
                                 JOptionPane.showMessageDialog(null, "Ya existe un cliente con CC" + cedula);
                             }
                         } catch (Administrador.EYaExiste ex) {
                             JOptionPane.showMessageDialog(null, ex.getMessage());
                         }
                     }
                 }

                 if (checkCarro.isSelected()) {
                     if (carroPlaca.getText().isEmpty() || carroColor.getText().isEmpty() || carroKilometraje.getText().isEmpty() || carroNumeroPuertas.getText().isEmpty() || carroTraccion.getText().isEmpty()) {
                         JOptionPane.showMessageDialog(null, "Por favor complete todos los campos (CARRO)");
                     } else {
                         Administrador a = new Administrador();
                         try {
                             if (!a.existeCedula(cedula)) {
                                 if (!a.existeVehiculo(crPlaca)) {
                                     Date hoy = Calendar.getInstance().getTime();
                                     try {
                                         a.addCliente(nombre, cedula, FN, direccion, telefono, correo, hoy, crPlaca, crColor, true, Integer.parseInt(crKilometraje), crLlantas, Integer.parseInt(crNumPuertas), crTraccion);
                                     } catch (Administrador.ENoExiste ex) {
                                         JOptionPane.showMessageDialog(null, ex.getMessage());
                                     } catch (Administrador.EVectorNulo ex) {
                                         JOptionPane.showMessageDialog(null, ex.getMessage());
                                     }
                                     
                                     JOptionPane.showMessageDialog(null, "Guardado Exitoso");
                                     this.dispose();
                                 } else {
                                     JOptionPane.showMessageDialog(null, "Ya existe un vehÃ­culo con placa: " + crPlaca);
                                 }
                                 
                             } else {
                                 JOptionPane.showMessageDialog(null, "Ya existe un cliente con CC" + cedula);
                             }
                         } catch (Administrador.EYaExiste ex) {
                             JOptionPane.showMessageDialog(null, ex.getMessage());
                         }

                     }
                 }

        	} else {
        		JOptionPane.showMessageDialog(null, "por favor ingrese una fecha válida");
        	}
           
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void checkCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCarroActionPerformed
        // TODO add your handling code here:
        if (checkMoto.isSelected()) {
            checkMoto.setSelected(false);
            checkCarro.setSelected(true);
        }
    }//GEN-LAST:event_checkCarroActionPerformed

    private void carroCheckLlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carroCheckLlantasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carroCheckLlantasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JCheckBox carroCheckLlantas;
    private javax.swing.JTextField carroColor;
    private javax.swing.JTextField carroKilometraje;
    private javax.swing.JTextField carroNumeroPuertas;
    private javax.swing.JTextField carroPlaca;
    private javax.swing.JTextField carroTraccion;
    private javax.swing.JCheckBox checkCarro;
    private javax.swing.JCheckBox checkMoto;
    private javax.swing.JTextField clienteCedula;
    private javax.swing.JTextField clienteCorreo;
    private javax.swing.JTextField clienteDireccion;
    private javax.swing.JTextField clienteFNAno;
    private javax.swing.JTextField clienteFNDia;
    private javax.swing.JTextField clienteFNMes;
    private javax.swing.JTextField clienteNombre;
    private javax.swing.JTextField clienteTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox motoCheckLlantas;
    private javax.swing.JTextField motoColor;
    private javax.swing.JTextField motoKilometraje;
    private javax.swing.JTextField motoPlaca;
    private javax.swing.JTextField motoTiempos;
    // End of variables declaration//GEN-END:variables
}
